## FASE 1 - Carga de datos

Los datos ya están divididos previamente en entrenamiento/producción

In [1]:
import pandas as pd

dataset_path = '../../../Datasets/TrainingDatasets/new_measurements_learning.csv'

training_data = pd.read_csv(dataset_path)

print(f'El dataset tiene {training_data.shape[0]} filas y {training_data.shape[1]} columnas')

training_data.head()

El dataset tiene 847457 filas y 16 columnas

,id,measure_id,monitor_id,landmark_id,landmark_type,dst_ip,ping_rtt1,ping_rtt2,ping_rtt3,ping_rtt4,ping_rtt5,ping_rtt_avg,ping_rtt_std,direct_distance_kms,init_time,end_time
0,139713,95.217.19.69_2024-11-27 13:31:04,monitor_5_Warsaw_PL,9404,ripe_anchor,95.217.19.69,43.396,43.285,43.153,43.413,43.361,43.3216,0.09509,934.999404,2024-11-27 13:31:04,2024-11-27 13:31:10
1,139714,95.217.19.69_2024-11-27 13:31:04,monitor_2_Frankfurt am Main_DE,9404,ripe_anchor,95.217.19.69,29.764,30.024,30.169,29.848,29.768,29.9146,0.15830,1530.246007,2024-11-27 13:31:04,2024-11-27 13:31:10
2,139715,95.217.19.69_2024-11-27 13:31:04,monitor_6_Milan_IT,9404,ripe_anchor,95.217.19.69,44.189,44.295,44.580,44.130,44.185,44.2758,0.16121,1954.678802,2024-11-27 13:31:04,2024-11-27 13:31:10
3,139716,95.217.19.69_2024-11-27 13:31:04,monitor_1_Madrid_ES,9404,ripe_anchor,95.217.19.69,58.439,58.898,58.747,58.634,58.173,58.5782,0.25197,2963.403860,2024-11-27 13:31:04,2024-11-27 13:31:10
4,139717,95.217.19.69_2024-11-27 13:31:04,monitor_3_Dublin_IE,9404,ripe_anchor,95.217.19.69,44.494,45.022,44.098,44.170,44.756,44.5080,0.34878,2031.641470,2024-11-27 13:31:04,2024-11-27 13:31:11

In [2]:
# Nos quedamos de training data por las entradas con un measure_id que aparezca 6 veces (los 6 monitores)
print(f"Número de entradas antes de eliminar medidas faltantes: {len(training_data)}")
training_data = training_data[training_data['measure_id'].map(training_data['measure_id'].value_counts()) == 6]
print(f"Número de entradas después de eliminar medidas faltantes: {len(training_data)}")

Número de entradas antes de eliminar medidas faltantes: 847457
Número de entradas después de eliminar medidas faltantes: 840324

In [3]:
# Representamos la cabecera
training_data.head()

,id,measure_id,monitor_id,landmark_id,landmark_type,dst_ip,ping_rtt1,ping_rtt2,ping_rtt3,ping_rtt4,ping_rtt5,ping_rtt_avg,ping_rtt_std,direct_distance_kms,init_time,end_time
0,139713,95.217.19.69_2024-11-27 13:31:04,monitor_5_Warsaw_PL,9404,ripe_anchor,95.217.19.69,43.396,43.285,43.153,43.413,43.361,43.3216,0.09509,934.999404,2024-11-27 13:31:04,2024-11-27 13:31:10
1,139714,95.217.19.69_2024-11-27 13:31:04,monitor_2_Frankfurt am Main_DE,9404,ripe_anchor,95.217.19.69,29.764,30.024,30.169,29.848,29.768,29.9146,0.15830,1530.246007,2024-11-27 13:31:04,2024-11-27 13:31:10
2,139715,95.217.19.69_2024-11-27 13:31:04,monitor_6_Milan_IT,9404,ripe_anchor,95.217.19.69,44.189,44.295,44.580,44.130,44.185,44.2758,0.16121,1954.678802,2024-11-27 13:31:04,2024-11-27 13:31:10
3,139716,95.217.19.69_2024-11-27 13:31:04,monitor_1_Madrid_ES,9404,ripe_anchor,95.217.19.69,58.439,58.898,58.747,58.634,58.173,58.5782,0.25197,2963.403860,2024-11-27 13:31:04,2024-11-27 13:31:10
4,139717,95.217.19.69_2024-11-27 13:31:04,monitor_3_Dublin_IE,9404,ripe_anchor,95.217.19.69,44.494,45.022,44.098,44.170,44.756,44.5080,0.34878,2031.641470,2024-11-27 13:31:04,2024-11-27 13:31:11

In [4]:
# Para estas primeras pruebas, nos vamos a quedar únicamente con los landmark_type ripe_anchor y ripe_probe
print(f"Número de entradas antes de eliminar dns y router intermedios: {len(training_data)}")
training_data = training_data[training_data['landmark_type'].isin(['ripe_anchor', 'ripe_probe'])]
print(f"Número de entradas después de eliminar dns y router intermedios: {len(training_data)}")

Número de entradas antes de eliminar dns y router intermedios: 840324
Número de entradas después de eliminar dns y router intermedios: 840324

In [5]:
# Guardamos el dataset en un archivo .csv en una carpeta temporal
training_data.to_csv('../tmp/training_data.csv', index=False)